### ISSUE TITLE
Your PHP installation appears to be missing the MySQL extension which is required by WordPress.

### ISSUE THREAD

**Issue by Duduz7** [HendGrow/walk-throughs#1] opened 2020-08-27 22:43 UTC
I have Php 7.4.3 and when I go to "http://localhost/info.php," Php runs normally, whats was my mistake, what is my installation lacking and how do I fix it?

![Screenshot from 2020-08-27 18-40-59](https://user-images.githubusercontent.com/63926330/91501967-e56ab180-e894-11ea-9ce5-df4f63fc795b.png)

![Screenshot from 2020-08-27 18-40-01](https://user-images.githubusercontent.com/63926330/91502085-3b3f5980-e895-11ea-978e-d398b955166d.png)

![Screenshot from 2020-08-27 18-42-14](https://user-images.githubusercontent.com/63926330/91502038-16e37d00-e895-11ea-9d69-9ea2e5c392cc.png)

**Comment by HendGrow** [comment] 2020-09-24 14:07
Hi Duduz7 

Ensure you using the right versions of the software. 
**WordPress 5.5.1***
**PHP 7.4** or greater
**MariaDB 10.1** or greater
If all in order confirm you ran the following:

_`sudo apt-get php7.4-mysql`_

Restart Apache 
_`sudo systemctl restart apache2`_

Let us know if this solves your issue.

**Comment by HendGrow** [comment] 2020-09-27 08:30
Hi Duduz7, 

You have not responded therefore we will provisonaly close this request. If the issue is not resolved please reach out to us.

**Closed as completed by HendGrow** 2020-09-27 08:30 UTC
